spring:
  application:
    name: registry

  config:
    import: optional:configserver:http://${CONFIG_HOST:localhost}:${CONFIG_PORT:8888}
  cloud:
    config:
      uri:
      fail-fast: false
      username: user
      password: ${CONFIG_PASS:dev}

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0