spring:
  application:
    name: account
  config:
    import: optional:configserver:http://${CONFIG_HOST:localhost}:${CONFIG_PORT:8888}
  cloud:
    config:
      uri: http://${CONFIG_HOST:localhost}:${CONFIG_PORT:8888}
      fail-fast: true
      password: ${CONFIG_PASS:dev}
      username: user
